- "Analyze retail transaction data to uncover sales trends, product performance, customer behavior, and regional revenue patterns, and provide actionable business recommendations to drive revenue growth, optimize inventory, and improve customer loyalty. Implement RFM analysis to segment customers based on recency, frequency, and monetary value, identifying high-value and loyal customers for targeted strategies."

In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\online_retail_II.xlsx (1)\online_retail_II.xlsx")

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df.shape

(525461, 8)

In [5]:
df.size

4203688

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [7]:
df.isna().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [8]:
df['Description'].fillna('No Descriptionn', inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_18828\1315723093.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Description'].fillna('No Descriptionn', inplace=True)

In [9]:
df.isna().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [10]:
df_customers = df[df['Customer ID'].notna()]

In [11]:
df_customers.reset_index(drop=True, inplace=True)

In [12]:
df_customers.isna().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [13]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417534 entries, 0 to 417533
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      417534 non-null  object
 1   StockCode    417534 non-null  object
 2   Description  417534 non-null  object
 3   Quantity     417534 non-null  int64
 4   InvoiceDate  417534 non-null  datetime64[ns]
 5   Price        417534 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      417534 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 25.5+ MB

In [14]:
df_customers.duplicated().any()

np.True_

In [15]:
df_customers = df[df['Customer ID'].notna()].copy()
df_customers.drop_duplicates(inplace=True)

In [16]:
df_customers.duplicated().any()

np.False_

In [17]:
df_customers['TotalAmount'] = df_customers['Quantity'] * df_customers['Price']

In [18]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 410763 entries, 0 to 525460
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      410763 non-null  object
 1   StockCode    410763 non-null  object
 2   Description  410763 non-null  object
 3   Quantity     410763 non-null  int64
 4   InvoiceDate  410763 non-null  datetime64[ns]
 5   Price        410763 non-null  float64
 6   Customer ID  410763 non-null  float64
 7   Country      410763 non-null  object
 8   TotalAmount  410763 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 31.3+ MB

In [19]:
df_sales = df_customers[df_customers['TotalAmount'] > 0].copy()

In [20]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400916 entries, 0 to 525460
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  object
 1   StockCode    400916 non-null  object
 2   Description  400916 non-null  object
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[ns]
 5   Price        400916 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      400916 non-null  object
 8   TotalAmount  400916 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 30.6+ MB

In [21]:
df_sales.rename(columns={
    'Customer ID': 'CustomerID',
    'InvoiceDate': 'InvoiceDate',
    'TotalAmount': 'TotalAmount'
}, inplace=True)

In [22]:
df_sales['CustomerID'] = df_sales['CustomerID'].astype(int)

In [23]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400916 entries, 0 to 525460
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  object
 1   StockCode    400916 non-null  object
 2   Description  400916 non-null  object
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[ns]
 5   Price        400916 non-null  float64
 6   CustomerID   400916 non-null  int64
 7   Country      400916 non-null  object
 8   TotalAmount  400916 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 30.6+ MB

In [ ]:
from sqlalchemy import create_engine


user = 'root'
password = 'your password'
host = 'localhost'   # or your server IP
port = 3306
database = 'retail'


engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}')

In [25]:
# Upload df_sales to existing table
df_sales.to_sql(name='retail_sales', con=engine, if_exists='append', index=False)
print("Data imported to SQL successfully!")

Data imported to SQL successfully!

In [ ]:
username = 'root'
password = 'your password'
database = 'retail'

# Create engine
engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@localhost:3306/{database}')

In [32]:
try:
    with engine.connect() as conn:
        print("Connected successfully!")
except Exception as e:
    print("Connection failed:", e)

Connected successfully!

In [33]:
rfm_sql = pd.read_sql("SELECT * FROM rfm_sql", con=engine)

In [39]:
rfm_sql['R_Score'] = pd.qcut(rfm_sql['Recency'], 5, labels=range(5,0,-1))
rfm_sql['F_Score'] = pd.qcut(rfm_sql['Frequency'].rank(method='first'), 5, labels=range(1,6))
rfm_sql['M_Score'] = pd.qcut(rfm_sql['Monetary'].rank(method='first'), 5, labels=range(1,6))
rfm_sql['RFM_Score'] = rfm_sql['R_Score'].astype(str) + rfm_sql['F_Score'].astype(str) + rfm_sql['M_Score'].astype(str)
rfm_sql.head(10)

   CustomerID  Recency  Frequency  Monetary R_Score F_Score M_Score RFM_Score
0       12346     5730         11    372.86       2       5       2       252
1       12347     5568          2   1323.32       5       2       4       524
2       12348     5639          1    222.16       2       1       1       211
3       12349     5608          3   2671.14       3       3       5       335
4       12351     5576          1    300.93       5       1       2       512
5       12352     5576          2    343.80       5       2       2       522
6       12353     5609          1    317.76       3       1       2       312
7       12355     5768          1    488.21       1       1       2       112
8       12356     5581          3   3560.30       4       3       5       435
9       12357     5589          2  12079.99       4       2       5       425

In [40]:
rfm_sql['RFM_Score'].value_counts()

RFM_Score
555    349
111    202
455    153
121    144
112    105
      ...
415      1
515      1
452      1
352      1
351      1
Name: count, Length: 117, dtype: int64

In [41]:
rfm_sql.to_sql(name='rfm_customers', con=engine, if_exists='replace', index=False)
print("RFM table uploaded successfully!")

RFM table uploaded successfully!